<?php

namespace Frontender\Core\Routes\Api;

use Frontender\Core\DB\Adapter;
use Frontender\Core\Routes\Helpers\CoreRoute;
use Frontender\Core\Routes\Traits\Authorizable;
use Slim\Http\Request;
use Slim\Http\Response;

class Blueprints extends CoreRoute {
	protected $group = '/api/blueprints';

	use Authorizable;

	protected function registerCreateRoutes() {
		parent::registerCreateRoutes();

		$this->app->put( '', function ( Request $request, Response $response ) {
			\Frontender\Core\Controllers\Blueprints::add( $request->getParsedBody() );

			return $response->withStatus( 200 );
		} );
	}

	protected function registerReadRoutes() {
		parent::registerReadRoutes();

		$this->app->get( '', function ( Request $request, Response $response ) {
			$json = Adapter::getInstance()->toJSON(
				\Frontender\Core\Controllers\Blueprints::browse()
			);

			return $response->withJson( $json );
		} );
	}

	protected function registerUpdateRoutes() {
		parent::registerUpdateRoutes(); // TODO: Change the autogenerated stub

		$this->app->post( '/preview', function ( Request $request, Response $response ) {
			$data = $request->getParsedBody();
			$blueprint = json_decode($data['data'], true);
			$page = [
				'template' => 'layouts/global.html.twig',
				'containers' => [
					$blueprint['definition']
				]
			];

			$json = \Frontender\Core\Controllers\Pages::sanitize($page);

			try {
				$page = $this->page;
				$this->language->set($request->getQueryParam('locale'));
//			$page->setName($attributes['page']);
//			$page->setParameters(['debug' => $this->settings['debug'], 'query' => $request->getQueryParams()]);
				$page->setData( $json );
				$page->setRequest( $request );
				$page->parseData();

				$response->getBody()->write($page->render());
			} catch (\Exception $e) {
				echo $e->getMessage();
				die('Called');
			} catch (\Error $e) {
				echo $e->getMessage();
				echo '<pre>';
				print_r(array_map(function($trace) {
					return $trace['file'] . '::' . $trace['line'];
				}, $e->getTrace()));
				echo '</pre>';
				die();
			}

			return $response;
		} );
	}
}