<?php

namespace Frontender\Core\Routes\Api;

use Frontender\Core\DB\Adapter;
use Frontender\Core\Routes\Helpers\CoreRoute;
use Frontender\Core\Routes\Traits\Authorizable;
use MongoDB\BSON\ObjectId;
use Slim\Http\Request;
use Slim\Http\Response;

class Controls extends CoreRoute {
	protected $group = '/api/controls';

	use Authorizable;

	protected function registerReadRoutes() {
		parent::registerReadRoutes(); // TODO: Change the autogenerated stub

		$this->app->get('', function(Request $request, Response $response) {
			$data = Adapter::getInstance()->collection('controls')->find()->toArray();
			$json = Adapter::getInstance()->toJSON($data);

			return $response->withJson($json)
			                ->withHeader('Access-Control-Allow-Origin', '*')
			                ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, Authorization')
			                ->withHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
		});

		$this->app->get('/{id}', function(Request $request, Response $response) {
			$data = Adapter::getInstance()->collection('controls')->findOne([
				'_id' => new ObjectId($request->getAttribute('id'))
			]);
			$json = Adapter::getInstance()->toJSON($data);

			return $response->withJson($json)
			                ->withHeader('Access-Control-Allow-Origin', '*')
			                ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, Authorization')
			                ->withHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
		});
	}
}